on:
  push:
jobs:
  ci-pipeline:
      runs-on: ubuntu-latest
      
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python 3.8
          uses: actions/setup-python@v5.1.0
          
            
            
        - name: Install pip
          run: |
            python -m pip install --upgrade pip
            
        - name: Bundle validate 
        - uses: databricks/setup-cli@main
        - run: databricks bundle validate

        - name: Bundle deploy
        - uses: databricks/setup-cli@main
        - run: databricks bundle deploy

