on:
  push:
jobs:
  ci-pipeline:
      runs-on: ubuntu-latest
      
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python 3.8
          uses: actions/setup-python@v5.1.0
          with:
            python-version: '3.8'
            cache: 'pip' # caching pip dependencies
            cache-dependency-path: setup.py
            
        - name: Install pip
          run: |
            python -m pip install --upgrade pip
            pip install databricks-cli==0.205.2
