on:
  push:
jobs:
  ci-pipeline:
      runs-on: ubuntu-latest
      
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        
        - uses: actions/setup-python@v5.1.0
          
            
            
        - run: python -m pip install --upgrade pip
            
       
        - uses: databricks/setup-cli@main


        - run: databricks bundle deploy 
          env:
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            DATABRICKS_BUNDLE_ENV: default








        
        
        # - run: databricks bundle validate
        #   env:
        #     DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
            
          

       
        # - uses: databricks/setup-cli@main
        # - run: databricks bundle deploy
        #   env:
        #     DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
    
